test

diff --git a/.github/actions/update-toc/action.yml b/.github/actions/update-toc/action.yml
--- a/.github/actions/update-toc/action.yml
+++ b/.github/actions/update-toc/action.yml
@@ -12,6 +12,9 @@ inputs:
   toc-file:
     description: 'The path to the toc.yml file'
     required: true
+  directory:
+    description: 'The directory of the library'
+    required: false
 
 outputs:
   updated:
@@ -60,7 +63,57 @@ runs:
           cat $YAML_PATH
 
     - name: Update YAML file for cheetah-lib-shared-dotnet
-      #if: ${{ github.repository == 'cheetah-lib-shared-dotnet' }}
+      if: ${{ github.repository == 'cheetah-lib-shared-dotnet' && inputs.directory == 'articles' }}
+      shell: bash
+      run: |
+          YAML_PATH="${{ inputs.toc-file }}"
+          cat $YAML_PATH
+
+          # Ensure yq is installed
+          if ! command -v yq &> /dev/null; then
+            echo "yq could not be found. Please install yq to use this script."
+            exit 1
+          fi
+
+          # Ensure the YAML file exists
+          if [ ! -f "$YAML_PATH" ]; then
+            echo "YAML file not found: $YAML_PATH"
+            exit 1
+          fi
+
+          # Extract the name 'v${{ inputs.version }}' from ${{ inputs.repo-name }} and store it in a variable
+          result=$(yq eval '.[] | select(.name == "${{ inputs.repo-name }}") | .items[] | select(.name == "v${{ inputs.version }}") | .name' "$YAML_PATH")
+
+          # Check if the result is empty
+          if [[ -z "$result" ]]; then
+              echo "'v${{ inputs.version }}' item does not exist in ${{ inputs.repo-name }}. Adding it now..."
+
+              # Add 'v${{ inputs.version }}' entry to ${{ inputs.repo-name }} using yq and add to the file
+              yq eval '
+                .[] |= (
+                  select(.name == "${{ inputs.repo-name }}") |=
+                    (.items |=
+                      ([
+                        .[] | select(.name == "latest")
+                      ] + 
+                      [
+                        {"name": "v${{ inputs.version }}", "href": "${{ inputs.repo-name }}/v${{ inputs.version }}/toc.yml", "homepage": "${{ inputs.repo-name }}/v${{ inputs.version }}/index.md"}
+                      ] + 
+                      [
+                        .[] | select(.name != "latest")
+                      ])
+                    )
+                )
+              ' -i "$YAML_PATH"
+
+              echo "'v${{ inputs.version }}' item has been added to ${{ inputs.repo-name }}."
+          else
+              echo "The 'v${{ inputs.version }}' item exists in ${{ inputs.repo-name }}: $result"
+          fi
+          cat $YAML_PATH
+
+    - name: Update YAML file for cheetah-lib-shared-dotnet
+      if: ${{ github.repository == 'cheetah-lib-shared-dotnet' && inputs.directory == 'api' }}
       shell: bash
       run: |
           YAML_PATH="${{ inputs.toc-file }}"
